# -*- coding: utf-8 -*-
"""GSARCnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfvQuA5rmds-NYMXKuRhn9AdivkMxmGl
"""

import torch
import torch.nn as nn
from models.lexnet import LexNet
from models.adnet import ADNet
from models.foca import FOCA
from models.afg import AFG

class GSARCNet(nn.Module):
    def __init__(self, d_model=256, num_classes=2):
        super(GSARCNet, self).__init__()
        self.lexnet = LexNet(output_dim=d_model)
        self.adnet = ADNet(d_model=d_model)
        self.foca = FOCA(d_model=d_model)
        self.afg = AFG(d_model=d_model)
        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, texts, audio_waveforms):
        text_embed = self.lexnet(texts)
        audio_embed = self.adnet(audio_waveforms)
        text_attended, audio_attended = self.foca(text_embed, audio_embed)
        fused_embed = self.afg(text_attended, audio_attended)
        pooled = fused_embed.mean(dim=1)
        logits = self.classifier(pooled)
        return logits
