# -*- coding: utf-8 -*-
"""confusionmatrix_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMNxVpgI4Lbgg_fjvS54GIHYR-Zt94Y0
"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

def classification_report_with_cm(true_labels, pred_labels):
    print("Classification Report:")
    print(classification_report(true_labels, pred_labels))
        cm = confusion_matrix(true_labels, pred_labels)
    plt.figure(figsize=(6,5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")
    plt.show()
