# -*- coding: utf-8 -*-
"""Lexnet.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkd3EoVYR9Ajqyw1qDVQNlPJenVSZUmc
"""

import torch
import torch.nn as nn
from transformers import BertModel, BertTokenizer

class LexNet(nn.Module):
    def __init__(self, bert_model_name='bert-base-uncased', output_dim=256, max_length=50):
        super(LexNet, self).__init__()
        self.tokenizer = BertTokenizer.from_pretrained(bert_model_name)
        self.bert = BertModel.from_pretrained(bert_model_name)
        self.fc = nn.Linear(self.bert.config.hidden_size, output_dim)
        self.layernorm = nn.LayerNorm(output_dim)
        self.max_length = max_length

    def forward(self, texts):
        encodings = self.tokenizer(
            texts,
            padding='max_length',
            truncation=True,
            max_length=self.max_length,
            return_tensors='pt'
        )
        input_ids = encodings['input_ids'].to(next(self.parameters()).device)
        attention_mask = encodings['attention_mask'].to(next(self.parameters()).device)

        outputs = self.bert(input_ids, attention_mask=attention_mask)
        cls_embeddings = outputs.last_hidden_state

        x = self.fc(cls_embeddings)
        x = self.layernorm(x)
        return x
